---
name: Create conan dump

on: [ push, pull_request ]

jobs:
  build-msvc:
    name: Windows build
    runs-on: windows-latest
    env:
      DXSDK_DIR: C:\apps\Microsoft DirectX SDK\
      BUILD_TOOLS_PATH: C:\apps\build-tools\
    steps:
      - run: echo $env:BUILD_TOOLS_PATH | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - uses: actions/checkout@v2.4.0

      - name: Install Microsoft DirectX SDK and Build tools
        shell: cmake -P {0}
        run: |
          file(MAKE_DIRECTORY $ENV{DXSDK_DIR})
          file(DOWNLOAD http://prdownloads.sourceforge.net/rigs-of-rods/DirectX-SDK.zip "$ENV{TMP}/DirectX.zip" SHOW_PROGRESS)
          execute_process(COMMAND ${CMAKE_COMMAND} -E tar xzf "$ENV{TMP}/DirectX.zip" WORKING_DIRECTORY "$ENV{DXSDK_DIR}")
          file(MAKE_DIRECTORY $ENV{BUILD_TOOLS_PATH})
          file(DOWNLOAD http://prdownloads.sourceforge.net/rigs-of-rods/build-tools.zip "$ENV{TMP}/build-tools.zip" SHOW_PROGRESS)
          execute_process(COMMAND ${CMAKE_COMMAND} -E tar xzf "$ENV{TMP}/build-tools.zip" WORKING_DIRECTORY "$ENV{BUILD_TOOLS_PATH}")

      - name: Cache conan
        uses: actions/cache@v2.1.7
        with:
          key: conan-root-${{ hashFiles('**/conanfile.txt') }}
          path: ~/.conan

      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1.10.0

      - name: Add conan remote
        run: conan remote add -f ror-deps https://artifactory.anotherfoxguy.com/artifactory/api/conan/rigs-of-rods
        shell: cmd

      - name: Dump Conan packages
        run: conan install . -b=missing -pr=./VS-2019-Rel
        shell: cmd

      - name: Upload dump folder
        uses: actions/upload-artifact@v2
        with:
          name: Deps_31_VS_2019_Release
          path: dump

      - name: Clean Conan pkgs
        run: conan remove "*" -fsb
        shell: cmd
