---
name: Create conan dump

on: [push, pull_request]

jobs:
  build-msvc:
    name: Windows build
    runs-on: windows-2019
    env:
      DXSDK_DIR: C:\apps\Microsoft DirectX SDK\
      BUILD_TOOLS_PATH: C:\apps\build-tools\
    steps:
      - run: echo $env:BUILD_TOOLS_PATH | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - uses: actions/checkout@v3

      - name: Install Build tools
        run: git clone https://git.anotherfoxguy.com/AnotherFoxGuy/build-tools.git %BUILD_TOOLS_PATH%
        shell: cmd

      - name: Cache conan packages
        uses: actions/cache@v3
        with:
          key: conan-windows-${{ hashFiles('conanfile.py') }}
          path: ~/.conan2

      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1.12.1

      - name: Add conan remote
        run: |
          conan profile detect --force
          conan remote add ror-conan https://git.anotherfoxguy.com/api/packages/rorbot/conan -f
        shell: cmd

      - name: Dump Conan packages
        run: conan install . -b=missing -pr=./VS-2019-Rel --deployer=full_deploy -of dependencies
        shell: cmd

      - name: Upload dump folder
        uses: actions/upload-artifact@v3
        with:
          name: Deps_31_VS_2019_Release
          path: dependencies

      - name: Clean Conan pkgs
        run: conan remove "*" -fsb
        shell: cmd
